# Generated by Django 3.0.4 on 2020-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name of algorithm')),
                ('description', models.TextField(blank=True, verbose_name='Description of algorithm')),
                ('big_o_notation', models.CharField(max_length=30, verbose_name='Bit O notation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
