# Generated by Django 3.0.4 on 2020-03-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg', '0002_algorithm_execution_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm_execution_result',
            name='timing',
            field=models.CharField(max_length=50),
        ),
    ]
